GET https://ci.jenkins.io/api/json
Accept: application/json

###

POST http://localhost:8080/createItem?name=MyJob
Content-Type: application/xml
Authorization: Basic d2VyYV9zdHJlbWVkbG93c2thOjExN2RiZGIyN2VkYmM3MTA0OTk4Nzk4ZDhhMmRkNmJlMGQ=

<project>
    <actions/>
    <description>This is a more detailed description for the Jenkins job. It provides information about the purpose of the job, the tasks it performs, and any other relevant details.</description>
    <keepDependencies>false</keepDependencies>
    <properties/>
    <scm class="hudson.scm.NullSCM"/>
    <canRoam>true</canRoam>
    <disabled>false</disabled>
    <blockBuildWhenDownstreamBuilding>false</blockBuildWhenDownstreamBuilding>
    <blockBuildWhenUpstreamBuilding>false</blockBuildWhenUpstreamBuilding>
    <triggers/>
    <concurrentBuild>false</concurrentBuild>
    <builders/>
    <publishers/>
    <buildWrappers/>
</project>

###

POST http://localhost:8080/createView?name=MyView
Content-Type: application/xml
Authorization: Basic d2VyYV9zdHJlbWVkbG93c2thOjExN2RiZGIyN2VkYmM3MTA0OTk4Nzk4ZDhhMmRkNmJlMGQ=

<listView>
    <name>MyView</name>
    <filterExecutors>false</filterExecutors>
    <filterQueue>false</filterQueue>
    <properties class="hudson.model.View$PropertyList"/>
    <jobNames>
        <comparator class="hudson.util.CaseInsensitiveComparator"/>
    </jobNames>
    <jobFilters/>
    <columns>
        <hudson.views.StatusColumn/>
        <hudson.views.WeatherColumn/>
        <hudson.views.JobColumn/>
        <hudson.views.LastSuccessColumn/>
        <hudson.views.LastFailureColumn/>
        <hudson.views.LastDurationColumn/>
        <hudson.views.BuildButtonColumn/>
    </columns>
    <recurse>false</recurse>
</listView>

###

POST http://localhost:8080/view/MyView/addJobToView?name=MyJob
Content-Type: application/xml
Authorization: Basic d2VyYV9zdHJlbWVkbG93c2thOjExN2RiZGIyN2VkYmM3MTA0OTk4Nzk4ZDhhMmRkNmJlMGQ=

###

POST http://localhost:8080/job/MyJob/build
Authorization: Basic d2VyYV9zdHJlbWVkbG93c2thOjExN2RiZGIyN2VkYmM3MTA0OTk4Nzk4ZDhhMmRkNmJlMGQ=

###

GET http://localhost:8080/api/json?pretty=true
Accept: application/json
Authorization: Basic d2VyYV9zdHJlbWVkbG93c2thOjExN2RiZGIyN2VkYmM3MTA0OTk4Nzk4ZDhhMmRkNmJlMGQ=

###

GET http://localhost:8080/api/json?tree=jobs[name],views[name,jobs[name]]{0,10}
Accept: application/json
Authorization: Basic d2VyYV9zdHJlbWVkbG93c2thOjExN2RiZGIyN2VkYmM3MTA0OTk4Nzk4ZDhhMmRkNmJlMGQ=

###

GET http://localhost:8080/api/json?tree=jobs[name,description,lastCompletedBuild[result],lastBuild[duration],nextBuildNumber]
Accept: application/json
Authorization: Basic d2VyYV9zdHJlbWVkbG93c2thOjExN2RiZGIyN2VkYmM3MTA0OTk4Nzk4ZDhhMmRkNmJlMGQ=

###

GET http://localhost:8080/job/NewJob3/api/json?tree=lastSuccessfulBuild[timestamp],lastFailedBuild[timestamp]
Authorization: Basic d2VyYV9zdHJlbWVkbG93c2thOjExN2RiZGIyN2VkYmM3MTA0OTk4Nzk4ZDhhMmRkNmJlMGQ=


