name: CI

on:
  push:
    branches:
      - main

jobs:
  run-test:
    name: 'Run tests'
    runs-on: ubuntu-latest

    steps:
      - name: Git clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'

      - name: Get list of changed files
        run: echo "LIST_OF_CHANGED_FILES=$(git diff --name-only origin/$GITHUB_HEAD_REF $(git merge-base origin/$GITHUB_HEAD_REF origin/main) | tr '\n' ';')" >> $GITHUB_ENV

      - name: Prepare Jenkins data
        run: |
          if [ -d "${{ github.workspace }}/jenkins_data" ]; then
          cat ${{ github.workspace }}/jenkins_data/jenkins_backupa* > ${{ github.workspace }}/jenkins_backup.tar
          echo "Backup tar created."
          md5sum ${{ github.workspace }}/jenkins_backup.tar
          else
          echo "Jenkins data directory does not exist."
          exit 1
          fi

      - name: Extract Jenkins data and set permission
        run: |
          if [ -f "./jenkins_backup.tar" ]; then
            mkdir -p ./jenkins_backup/var/jenkins_home
            tar -xvf ./jenkins_backup.tar -C ./jenkins_backup
            chmod -R 777 ./jenkins_backup/var/jenkins_home
            echo "Extraction and permission setting completed."
          else
            echo "Jenkins backup tar file does not exist."
            exit 1
          fi

      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Docker start
        run: docker run --rm --detach -p 8080:8080 -v ${{ github.workspace }}/jenkins_backup/var/jenkins_home:/var/jenkins_home jenkins/jenkins:2.440.2-lts-jdk17

      - name: Wait for the Jenkins
        run: ./.github/wait-for-jenkins.sh

      - name: Install FFMPEG
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Run FFMPEG
        run: |
          Xvfb :99 &
          echo "DISPLAY=:99" >> $GITHUB_ENV
          ffmpeg -video_size 1024x768 -framerate 25 -f x11grab -i :99.0 output.mp4 &

      - name: Maven test
        run: mvn test
        env:
          CHROME_OPTIONS: --remote-allow-origins=*;--disable-gpu;--no-sandbox;--disable-dev-shm-usage;--headless=new;--window-size=1920,1080
          APP_OPTIONS: host=localhost;port=8080;admin.username=${{ secrets.ADMIN_USERNAME }};admin.password=${{ secrets.ADMIN_PASSWORD }}
          CI_RUN: true

      - name: Attach screenshots and reports
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: screenshots-and-report
          path: |
            screenshots
            output.mp4

      - name: Test Reporter
        uses: dorny/test-reporter@v1.8.0
        if: success() || failure()
        with:
          name: JenkinsQA Project Test Report
          path: target/surefire-reports/TEST-*.xml
          reporter: java-junit
